CREATE TABLE users (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR(100) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "surname" VARCHAR(100) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE todos (
  "id" SERIAL PRIMARY KEY,
  "user_id" INTEGER NOT NULL REFERENCES users(id),
  "title" TEXT NOT NULL,
  "descption" TEXT NOT NULL,
  "done" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);